"""
@cernodile/py-deltaparser

A Python script to convert Growtopia's items.dat to human-readable indexable format.
File: datatables.py
Purpose: To generate user-friendly category types for Cernodile's World Planner (updated by healLV)
License: See LICENSE.txt in project root directory.
"""
PlannerTypes = [
"Fist",
"Wrench",
"Door",
"Lock",
"Gems",
"Treasure",
"Deadly Block",
"Trampoline Block",
"Consumable",
"Gateway",
"Sign",
"SFX Foreground",
"Toggleable Foreground",
"Main Door",
"Platform",
"Bedrock",
"Pain Block (Lava)",
"Foreground Block",
"Background Block",
"Seed",
"Clothes",
"Animated Foreground Block",
"SFX Background",
"Toggleable Background",
"Bouncy Block",
"Pain Block",
"Portal",
"Checkpoint",
"Sheet Music",
"Slippery Block",
"EMPTY",
"Switch Block",
"Chest",
"Mailbox",
"Bulletin Board",
"Event Mystery Block",
"Random Block",
"Component (Unusable by itself)",
"Provider",
"Chemical Combiner",
"Achievement Block",
"Weather Machine",
"Scoreboard",
"Sungate",
"Profile",
"Toggleable Deadly Block",
"Heart Monitor",
"Donation Box",
"EMPTY",
"Mannequin",
"Security Camera",
"Magic Egg",
"Game Generator Related Block",
"Game Generator",
"Xenonite Crystal",
"Phone Booth",
"Crystal",
"Crime Villain",
"Clothes Compactor",
"Spotlight",
"Pushing Block",
"Display Block",
"Vending Machine",
"Fish Tank Port",
"Fish",
"Solar Collector",
"Forge",
"Giving Tree",
"Giving Tree Stump",
"Steam Block",
"Steam Pain block",
"Steam Music block",
"Silkworm",
"Sewing Machine",
"Country Flag",
"Lobster Trap",
"Painting Easel",
"Battle Pet Cage",
"Pet Trainer",
"Steam Engine",
"Lock-Bot",
"Weather Machine - Heatwave",
"Spirit Storage",
"Display Shelf",
"VIP Entrance",
"Challenge Timer",
"Challenge Flag",
"Fish Wall Mount",
"Portrait",
"Weather Machine - Heatwave",
"Fossil",
"Fossil Prep Station",
"DNA Processor",
"Blaster",
"Valhowla Treasure",
"Chemsynth Processor",
"Chemsynth Tank",
"Untrade-a-Box",
"Oven",
"Audio Block",
"Geiger Charger",
"Adventure Begin",
"Tomb Robber",
"Balloon-O-Matic",
"Gateway (Punch)",
"Gateway (Grow)",
"Gateway (Build)",
"Artifact",
"Jelly Block",
"Training Port",
"Fishing Block",
"Magplant",
"Magplant Remote",
"CyBlock Bot",
"CyBlock Command",
"Lucky Token",
"GrowScan 9000",
"Containment Field Power Node",
"Spirit Board",
"World Architect",
"Startopia Block",
"Self-Destruct Block",
"Gravity Well/Weather Vane",
"Tesseract Manipulator",
"Heart of Gaia",
"Techno-Organic Engine",
"Storm Cloud",
"Phased block",
"Mud Puddle",
"Root Cutting",
"Password Storage",
"Phased Block Two",
"Bomb",
"",
"Weather Machine - Infinity",
"Slime",
"Acid"
]
